import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
      <h1 className={styles.title}>Hunting Coder</h1>
      <p className={styles.subtitle}>A blog for hunting coders by a hunting coder</p>
      <div className={styles.grid}>
        <a href="#" className={styles.card}>
          <h2>Documentation →</h2>
          <p>Find in-depth information about Next.js features and API.</p>
        </a>
        <a href="#" className={styles.card}>
          <h2>Learn →</h2>
          <p>Learn about Next.js in an interactive course with quizzes!</p>
        </a>
        <a href="#" className={styles.card}>
          <h2>Examples →</h2>
          <p>Discover and deploy boilerplate example Next.js projects.</p>
        </a>
        <a href="#" className={styles.card}>
          <h2>Deploy →</h2>
          <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
        </a>
      </div>
    </div>
  </>)
};